version: 2

aliases:
  - &setup_miniconda
    name: setup_miniconda
    command: |
       mkdir -p workspace
       git clone -b validateNightly git@github.com:CDAT/cdat workspace/cdat
       # install_miniconda.py installs miniconda3 under $WORKDIR/miniconda
       python workspace/cdat/scripts/install_miniconda.py -w $WORKDIR -p 'py3'

  - &conda_rerender
    name: conda_rerender
    command: |
       git clone -b conda_forge_pinning https://github.com/CDAT/conda-recipes.git $WORKDIR/conda-recipes 
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       BUILD_SCRIPT="$WORKDIR/conda-recipes/build_tools/conda_build.py"
       python $BUILD_SCRIPT -w $WORKDIR -l $LAST_STABLE -B 0 -p $PKG_NAME -b $CIRCLE_BRANCH --do_rerender

  - &conda_build
    name: conda_build
    command: |
       echo "cat $WORKDIR/vtk-cdat/recipe/meta.yaml"
       cat $WORKDIR/vtk-cdat/recipe/meta.yaml
       echo "ls -l $WORKDIR/vtk-cdat/.ci_support"
       ls -l $WORKDIR/vtk-cdat/.ci_support
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       conda config --add channels conda-forge --force
       conda config --set channel_priority strict
       BUILD_SCRIPT="$WORKDIR/conda-recipes/build_tools/conda_build.py"
       python $BUILD_SCRIPT -w $WORKDIR -p $PKG_NAME --build_version $BUILD_VARIANT_VER --do_build

  - &conda_upload
    name: conda_upload
    command: |
       if [[ $CIRCLE_BRANCH != "master" ]]; then
          exit 0
       fi
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       UPLOAD_OPTIONS="-t $CONDA_UPLOAD_TOKEN upload -u $USER -l $LABEL"
       anaconda $UPLOAD_OPTIONS linux_build/miniconda/conda-bld/linux-64/$PKG_NAME-$VERSION.`date +%Y*`0.tar.bz2 --force
       anaconda $UPLOAD_OPTIONS macos_build/miniconda/conda-bld/osx-64/$PKG_NAME-$VERSION.`date +%Y*`0.tar.bz2 --force

  - &install_ninja
    name: install_ninja
    command: |
       git clone git://github.com/ninja-build/ninja.git $WORKDIR/ninja
       cd $WORKDIR/ninja
       git checkout release
       ./configure.py --bootstrap

jobs:
   macos_setup:
      macos:
         xcode: "11.2.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         PKG_NAME: "vtk-cdat"
         LAST_STABLE: "8.2.0.8.2"
      steps:
         - run: *setup_miniconda
         - run: *conda_rerender
         - persist_to_workspace:
              root: .
              paths: 
                 - macos_build

   linux_setup:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "vtk-cdat"
         LAST_STABLE: "8.2.0.8.2"
      steps:
         - attach_workspace:
              at: .
         - run: *setup_miniconda
         - run: *install_ninja
         - run: *conda_rerender
         - run: ls -l $WORKDIR
         - run: ls -l $WORKDIR/vtk-cdat
         - run: ls -l $WORKDIR/vtk-cdat/.ci_support
         - run: ls -l $WORKDIR/vtk-cdat/recipe
         - persist_to_workspace:
              root: .
              paths:
                 - linux_build

   macos_vtk_cdat_py2_mesaFalse:
      macos:
         xcode: "11.2.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         PKG_NAME: "vtk-cdat"
         ENV_NAME: "test_vtk_cdat"
         LAST_STABLE: "8.2.0.8.2"
         CONDA_PY_VER: "python<3"
         BUILD_VARIANT_VER: "2.7vtk_with_osmesaFalse"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - persist_to_workspace:
              root: .
              paths:
                 - macos_build/miniconda/conda-bld/osx-64/vtk-cdat*tar.bz2

   macos_vtk_cdat_py2_mesaTrue:
      macos:
         xcode: "11.2.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         PKG_NAME: "vtk-cdat"
         ENV_NAME: "test_vtk_cdat"
         LAST_STABLE: "8.2.0.8.2"
         CONDA_PY_VER: "python<3"
         BUILD_VARIANT_VER: "2.7vtk_with_osmesaTrue"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - persist_to_workspace:
              root: .
              paths:
                 - macos_build/miniconda/conda-bld/osx-64/vtk-cdat*tar.bz2

   macos_vtk_cdat_py37_mesaFalse:
      macos:
         xcode: "11.2.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         PKG_NAME: "vtk-cdat"
         ENV_NAME: "test_vtk_cdat"
         LAST_STABLE: "8.2.0.8.2"
         CONDA_PY_VER: "python>=3.7,<3.8"
         BUILD_VARIANT_VER: "3.7vtk_with_osmesaFalse"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - persist_to_workspace:
              root: .
              paths:
                 - macos_build/miniconda/conda-bld/osx-64/vtk-cdat*tar.bz2

   macos_vtk_cdat_py37_mesaTrue:
      macos:
         xcode: "11.2.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         PKG_NAME: "vtk-cdat"
         ENV_NAME: "test_vtk_cdat"
         LAST_STABLE: "8.2.0.8.2"
         CONDA_PY_VER: "python>=3.7,<3.8"
         BUILD_VARIANT_VER: "3.7vtk_with_osmesaTrue"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - persist_to_workspace:
              root: .
              paths:
                 - macos_build/miniconda/conda-bld/osx-64/vtk-cdat*tar.bz2

   linux_vtk_cdat_py2_mesaFalse:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "vtk-cdat"
         ENV_NAME: "test_vtk_cdat"
         LAST_STABLE: "8.2.0.8.2"
         CONDA_PY_VER: "python<3"
         BUILD_VARIANT_VER: "2.7vtk_with_osmesaFalse"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - persist_to_workspace:
              root: .
              paths:
                 - linux_build/miniconda/conda-bld/linux-64/vtk-cdat*tar.bz2

   linux_vtk_cdat_py2_mesaTrue:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "vtk-cdat"
         ENV_NAME: "test_vtk_cdat"
         LAST_STABLE: "8.2.0.8.2"
         CONDA_PY_VER: "python<3"
         BUILD_VARIANT_VER: "2.7vtk_with_osmesaTrue"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - persist_to_workspace:
              root: .
              paths:
                 - linux_build/miniconda/conda-bld/linux-64/vtk-cdat*tar.bz2

   linux_vtk_cdat_py37_mesaFalse:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "vtk-cdat"
         ENV_NAME: "test_vtk_cdat"
         LAST_STABLE: "8.2.0.8.2"
         CONDA_PY_VER: "python>=3.7,<3.8"
         BUILD_VARIANT_VER: "3.7vtk_with_osmesaFalse"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - persist_to_workspace:
              root: .
              paths:
                 - linux_build/miniconda/conda-bld/linux-64/vtk-cdat*tar.bz2

   linux_vtk_cdat_py37_mesaTrue:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "vtk-cdat"
         ENV_NAME: "test_vtk_cdat"
         LAST_STABLE: "8.2.0.8.2"
         CONDA_PY_VER: "python>=3.7,<3.8"
         BUILD_VARIANT_VER: "3.7vtk_with_osmesaTrue"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build
         - persist_to_workspace:
              root: .
              paths:
                 - linux_build/miniconda/conda-bld/linux-64/vtk-cdat*tar.bz2

   upload:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         PKG_NAME: "vtk-cdat"
         VERSION: "8.2.0.8.2"
         USER: "cdat"
         LABEL: "linatest"
      steps:
         - attach_workspace:
              at: .
         - run: pwd
         - run: ls -l
         - run: ls -l macos_build
         - run: ls -l macos_build/miniconda/conda-bld/osx-64
         - run: ls -l linux_build
         - run: ls -l linux_build/miniconda/conda-bld/linux-64
         - run: *conda_upload

workflows:
   version: 2
   cdtime:
      jobs:
         - macos_setup
         - linux_setup
         - macos_vtk_cdat_py2_mesaFalse:
              requires:
                 - macos_setup
         #- macos_vtk_cdat_py2_mesaTrue:
         #     requires:
         #        - macos_setup
         #- macos_vtk_cdat_py37_mesaFalse:
         #     requires:
         #        - macos_setup
         #- macos_vtk_cdat_py37_mesaTrue:
         #     requires:
         #        - macos_setup
         - linux_vtk_cdat_py2_mesaFalse:
              requires:
                 - linux_setup
         #- linux_vtk_cdat_py2_mesaTrue:
         #     requires:
         #        - linux_setup
         #- linux_vtk_cdat_py37_mesaFalse:
         #     requires:
         #        - linux_setup
         #- linux_vtk_cdat_py37_mesaTrue:
         #     requires:
         #        - linux_setup
         - upload:
              requires:
                 - macos_vtk_cdat_py2_mesaFalse
                 #- macos_vtk_cdat_py2_mesaTrue
                 #- macos_vtk_cdat_py37_mesaFalse
                 #- macos_vtk_cdat_py37_mesaTrue
                 - linux_vtk_cdat_py2_mesaFalse
                 #- linux_vtk_cdat_py2_mesaTrue
                 #- linux_vtk_cdat_py37_mesaFalse
                 #- linux_vtk_cdat_py37_mesaTrue
