version: 2

aliases:
  - &setup_miniconda
    name: setup_miniconda
    command: |
       mkdir -p workspace
       git clone -b validateNightly git@github.com:CDAT/cdat workspace/cdat
       # install_miniconda.py installs miniconda3 under $WORKDIR/miniconda
       python workspace/cdat/scripts/install_miniconda.py -w $WORKDIR -p 'py3'

  - &build_vtk_cdat
    name: build_vtk_cdat
    command: |
       git clone -b sync_recipe https://github.com/CDAT/conda-recipes.git $WORKDIR/conda-recipes 
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       python $WORKDIR/conda-recipes/build_tools/conda_build_upload.py -w $WORKDIR -l $LAST_STABLE -B 0 -p vtk-cdat


jobs:
   macos_vtk_cdat:
      macos:
         xcode: "11.2.0"
      environment:
         WORKDIR: "/users/distiller/project/workdir"
         LAST_STABLE: "8.2.0.8.2"
      steps:
         - checkout
         - run: *setup_miniconda
         - run: *build_vtk_cdat

   linux_vtk_cdat:
      docker:
         - image: circleci/python:latest
      resource_class: large
      environment:
         WORKDIR: "/users/distiller/project/workdir"
         LAST_STABLE: "8.2.0.8.2"
      steps:
         - checkout
         - run: *setup_miniconda
         - run: *build_vtk_cdat

workflows:
   version: 2
   vcs:
      jobs:
         - macos_vtk_cdat
         - linux_vtk_cdat
